#!/bin/bash
(
echo "// Autogenerated by generate_features.sh"
for feature in \
	M5STACK_SDCARD \
	M5STACK_NETWORK \
	M5STACK_SPEAKER \
	M5STACK_QRCODE \
	M5STACK_JPEG \
	M5STACK_BMP \
	M5STACK_PNG \
	M5STACK_LORA \
; do
	echo "#ifndef $feature"
	echo "#define $feature 1"
	echo "#endif"
	echo "#if $feature == 1"
	echo "#warning $feature enabled"
	echo "#endif"
done
) > ./src/M5StackFeatures.h