// Autogenerated by generate_features.sh
#ifndef M5STACK_SDCARD
#define M5STACK_SDCARD 1
#endif
#ifndef M5STACK_NETWORK
#define M5STACK_NETWORK 1
#endif
#ifndef M5STACK_SPEAKER
#define M5STACK_SPEAKER 1
#endif
#ifndef M5STACK_QRCODE
#define M5STACK_QRCODE 1
#endif
#ifndef M5STACK_JPEG
#define M5STACK_JPEG 1
#endif
#ifndef M5STACK_BMP
#define M5STACK_BMP 1
#endif
#ifndef M5STACK_PNG
#define M5STACK_PNG 1
#endif
#ifndef M5STACK_LORA
#define M5STACK_LORA 1
#endif
